package projeto.gui;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Matheus
 */
public class TelaFundo extends javax.swing.JPanel {
    
    BufferedImage imagemFundo;

    /**
     * Creates new form TelaFundo
     */
    public TelaFundo() {
        initComponents();
        
        try {
            this.imagemFundo = ImageIO.read(new File("C:\\Users\\Matheus\\Desktop\\Botoes\\GabsMain.png"));
        } catch (IOException ex) {
            Logger.getLogger(TelaFundo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponents(g);
        
        g.drawImage(imagemFundo, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(750, 422));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    /*ImageIcon fundo = new ImageIcon(getClass().getResource("/images/fundo.png"));
    @Override
    protected void paintComponent(Graphics g) {
	super.paintComponent(g);
	Graphics2D g2d = (Graphics2D) g.create();
	g2d.drawImage(fundo.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);
	g2d.dispose();
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
